# THIS FILE CONTAINS SOME CONSTANTS 

TYPE_CSI_CLIENT = 0
TYPE_FILE_TRANSFER_CLIENT = 1
TYPE_ANDROID_CLIENT = 2

# Key
KEY_CSI_CLIENT = 'clkj209cjE!4k2GV#w02'
KEY_FILE_TRANSFER_CLIENT = '#N2nb023flkn3lkj%!df'
KEY_ANDROID_CLIENT = 'b0D^GV#ADG213kjhb0#G'

# Server parameters
BUFFER_SIZE = 2048
SLEEP_TIME = 0.1
FILE_CLOSE_TIME = 3600

# Server Event
EVENT_START_CSI = 0
EVENT_STOP_CSI = 1
EVENT_SERVER_STATUS = 2
EVENT_CLOSE_CONNECTION = 3